name: Build

# Controls when the workflow will run
on:
  # PUSH to main branch
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: sudo bash ./build-inside-vm.sh
      # Expected output files are:
      # - RebornOS-ARM-cloudimg-YYYY-MM-DD.qcow2
      # - RebornOS-ARM-cloudimg-YYYY-MM-DD.qcow2.SHA256
      # - RebornOS-ARM-generic-YYYY-MM-DD.qcow2.SHA256
      # - RebornOS-ARM-generic-YYYY-MM-DD.qcow2
      # Upload the output files as seperate artifact files
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RebornOS-ARM
          path: |
            RebornOS-ARM-cloudimg-*.qcow2
            RebornOS-ARM-cloudimg-*.qcow2.SHA256
            RebornOS-ARM-generic-*.qcow2.SHA256
            RebornOS-ARM-generic-*.qcow2
      # Cleanup the output files and ./tmp folder
      - name: Clean up
        run: |
          sudo rm -rf ./tmp
          sudo rm -rf ./output/*
        

      